# Generated by Django 3.0.8 on 2022-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
